#!/usr/bin/env bash
USR=`logname`

case $USER in
    "RAM_maint") INDEX="/protocols/r1.json";;
    "maint") INDEX="/protocols/ltp.json";;
    * ) echo "This script is meant to be run from maint or RAM_maint not $USR";
        exit;;
esac

REPO="$HOME/index_file_tracker/"
echo "$REPO"
TIME=$(date "+%Y.%m.%d at %H.%M.%S")
cp "$INDEX" "$REPO"

cd "$REPO"
# we don't have git >1.8, so change directories
# git -C "$REPO" add .
git add .
git commit -m "Checkpoint for modifications made $TIME"
cd -


if [[ ${HOSTNAME:0:4} != "node" ]]; then
    while true; do
        echo "This script is best run from a node not the headnode (use qlogin)"
        read -p "Are you sure you want to continue? " yn
        case $yn in
            [Nn]* ) exit;;
            [Yy]* ) break;;
            * ) echo "Please answer y/n";;
        esac
    done
fi

#USER_HOME=`eval echo ~$USR`
#XAUTH_LINE=`xauth -f $USER_HOME/.Xauthority list | tail -1`
#xauth add $XAUTH_LINE
source ~/.bashrc
source activate event_creation
python -m event_creation.submission.convenience "$@"
